local config = require('oil.config')
local test_util = require('spec.test_util')

describe('config', function()
  after_each(function()
    test_util.reset_editor()
  end)

  it('uses defaults when setup() is called with no args', function()
    config.setup()
    assert.is_false(config.delete_to_trash)
    assert.equals(2000, config.cleanup_delay_ms)
    assert.equals(2, config.column_gap)
  end)

  it('applies explicit opts', function()
    config.setup({ delete_to_trash = true, cleanup_delay_ms = 5000 })
    assert.is_true(config.delete_to_trash)
    assert.equals(5000, config.cleanup_delay_ms)
  end)
end)
